name: tests

on: [push, pull_request]

jobs:
  windows:
    name: "py-${{ matrix.config.python }} lib-${{ matrix.config.ffmpeg }} ${{matrix.config.os}}"
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, python: 3.7, ffmpeg: "5.1"}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Conda
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda config --set always_yes true
        conda config --add channels conda-forge
        conda create -q -n pyav \
          cython \
          numpy \
          pillow \
          python=${{ matrix.config.python }} \
          setuptools

    - name: Build
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda activate pyav
        curl -L -o ffmpeg.7z https://www.gyan.dev/ffmpeg/builds/packages/ffmpeg-5.1.2-full_build-shared.7z
        7z x ffmpeg.7z -r -o$CONDA_PREFIX/
        echo "$CONDA_PREFIX\\ffmpeg-5.1.2-full_build-shared\\*.* $CONDA_PREFIX\\Library\\"
        xcopy "$CONDA_PREFIX\\ffmpeg-5.1.2-full_build-shared\\*.*" "$CONDA_PREFIX\\Library\\"
        ls $CONDA_PREFIX/Library
        ls $CONDA_PREFIX/Library/lib
        python setup.py build_ext --inplace --ffmpeg-dir=$CONDA_PREFIX/Library/

    - name: Test
      shell: bash
      run: |
        . $CONDA/etc/profile.d/conda.sh
        conda activate pyav
        python setup.py test
